version: '3.6'

services:
  rivers.run:
    image: rivers.run
    restart: always
    environment:
      - VIRTUAL_HOST=rivers.run
      - VIRTUAL_PORT=8080
      - LETSENCRYPT_HOST=rivers.run
      - LETSENCRYPT_EMAIL=support@rivers.run
    volumes:
        - ./server/data/notifications:/rivers.run/server/data/notifications
        - ./server/logs:/rivers.run/server/logs
    expose:
      - 8080

networks:
  default:
    external:
      name: nginx-proxy
