services:
  rivers.run:
    image: rivers.run
    restart: always
    environment:
      - VIRTUAL_HOST=rivers.run
      - VIRTUAL_PORT=8080
      - LETSENCRYPT_HOST=rivers.run
      - LETSENCRYPT_EMAIL=support@rivers.run
    volumes:
        - ./server/data:/rivers.run/server/data
        - ./server/logs:/rivers.run/server/logs
    expose:
      - 8080

  www-redirect:
    image: schmunk42/nginx-redirect
    container_name: rivers.run-www-redirect
    environment:
      - VIRTUAL_HOST=www.rivers.run
      - LETSENCRYPT_HOST=www.rivers.run
      - LETSENCRYPT_EMAIL=support@rivers.run
      - SERVER_REDIRECT=rivers.run
      - SERVER_REDIRECT_SCHEME=https

networks:
  default:
    name: nginx-proxy
    external: true
