services:
  rivers.run:
    image: rivers.run
    restart: always
    environment:
      - VIRTUAL_HOST=rivers.run
      - VIRTUAL_PORT=8080
      - LETSENCRYPT_HOST=rivers.run
      - LETSENCRYPT_EMAIL=support@rivers.run
    volumes:
        - ./server/data:/rivers.run/server/data
        - ./server/logs:/rivers.run/server/logs
    expose:
      - 8080

networks:
  default:
    name: nginx-proxy
    external: true
