name = "rivers-run-api"
main = "src/index.ts"
compatibility_date = "2026-04-15"
compatibility_flags = ["nodejs_compat"]


# D1 Database Binding
[[d1_databases]]
binding = "DB" # Available in your Worker as env.DB
database_name = "rivers-db"
database_id = "d52e56f5-d59f-4e59-b2e0-7b8b7a8dde71"
  
[[r2_buckets]]
binding = "FLOW_STORAGE"
bucket_name = "flowdata"
  
[[routes]]
pattern = "api.rivers.run"
custom_domain = true


